### ISSUE TITLE
循环绑定的事件，参数无法正常获取

### ISSUE THREAD

**Issue by gandao** [RubyLouvre/anu#274]
在一个三重循环里绑定一个事件，在触发后，获取的参数为最后一个循环传入的数据

**Comment by gandao** [comment]
下面代码中的onTap绑定的getDate方法，触发后传递的参数值一直为循环最后一个的值
`{this.state.calendarArray.map(function(month, idx) {
            return (
              <div key={idx}>
                <div class="e-month">
                  <div class="b-header">{month.date}</div>
                  {month.daysArray.map(function(itemRow, Row) {
                    return (
                      <div class="b-row" key={Row}>
                        {itemRow.map(function(item1) {
                          return (
                            <block key={item1}>
                              {item1.isBlank ? (
                                <div class="item" />
                              ) : (
                                <div onTap={this.getDate.bind(this,item1)} class={'item item-a ' + (item1.isWeekend ? 'weekend' : '')}>
                                  <div class="day">{item1.showDate}</div>
                                </div>
                              )}
                            </block>
                          );
                        })}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}`

**Comment by gandao** [comment]
```javascript
import React from '@react';
import './index.less';

class P extends React.Component {
  constructor() {
    super();
    this.state = {
      calendarArray: [],
      week: ['日', '一', '二', '三', '四', '五', '六']
    };
  }
  multiSelectFinish() {
    console.log('multiSelectFinish');
  }
  dateSelected() {
    console.log('dateSelected');
  }
  componentDidMount() {
    // 显示月份数
    const SHOWMONTH = 3;

    let data = [],
      yearMonth = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
      today = new Date(),
      year = today.getFullYear(),
      month = today.getMonth();

    for (var i = 0; i < SHOWMONTH; i++) {
      var item1 = {},
        iYear = year,
        iMonth = month;

      // 判断是否增加年份
      if (iMonth + i < 13) {
        iMonth += i;
      } else {
        iYear += 1;
        iMonth = iMonth + i - 12;
      }

      item1.date = iYear + '年' + iMonth + '月';
      let daysArray = [];

      // 判断是否为闰年
      if ((iYear % 4 === 0 && iYear % 100 !== 0) || iYear % 400 === 0) {
        yearMonth[1] = 29;
      } else {
        yearMonth[1] = 28;
      }

      let dayIndex = 1;
      for (var j = 0; j < 6; j++) {
        let arr = [];
        let firstDay = -1;
        // 判断第一天是周几
        if (j === 0) {
          firstDay = new Date(iYear, iMonth - 1, 1).getDay();
        }
        // 是否遍历完当月日期
        if(dayIndex > yearMonth[iMonth-1]) {
          break;
        }
        // 
        for (var k = 0; k < 7; k++) {
          if (firstDay !== -1 && k < firstDay) {
            arr.push({ isBlank: true });
          } else {
            if (dayIndex <= yearMonth[iMonth - 1]) {
              var item = {
                isBlank: false,
                showDate: dayIndex,
                isWeekend: k === 0 || k === 6 ? true : false,
                date: new Date(iYear,iMonth-1,dayIndex++)
              };
              arr.push(item);
            } else {
              arr.push({ isBlank: true });
            }
          }
        }
        daysArray.push(arr);
      }
      item1.daysArray = daysArray;
      data.push(item1);
    }
    this.setState({ calendarArray: data });
    console.log(data);
  }
  getDate(date) {
    var app = getApp()
    app.globalData.dateSelect = date;
    console.log(date);
  }
  render() {
    return (
      <div class="calendar">
        <div class="e-head">
          {this.state.week.map(function(item, idx) {
            return (
              <block key={item}>
                {idx == 0 || idx == 6 ? (
                  <view class="w s">{item}</view>
                ) : (
                  <view class="w">{item}</view>
                )}
              </block>
            );
          })}
        </div>
        <scroll-view class="m-calendar" scroll-y="true" scroll-into-div={this.state.todivId}>
          {this.state.calendarArray.map(function(month, idx) {
            return (
              <div key={idx}>
                <div class="e-month">
                  <div class="b-header">{month.date}</div>
                  {month.daysArray.map(function(itemRow, Row) {
                    return (
                      <div class="b-row" key={Row}>
                        {itemRow.map(function(item1) {
                          return (
                            <block key={item1}>
                              {item1.isBlank ? (
                                <div class="item" />
                              ) : (
                                <div onTap={this.getDate.bind(this,item1)} class={'item item-a ' + (item1.isWeekend ? 'weekend' : '')}>
                                  <div class="day">{item1.showDate}</div>
                                </div>
                              )}
                            </block>
                          );
                        })}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </scroll-view>
      </div>
    );
  }
}

export default P;
```

**Comment by gandao** [comment]
```css
page {
    height: 100%;
}
.m-calendar {
    margin-top: 42px;
    background-color:#fff;
    height: 100%;
    overflow: hidden;
}
.e-head {
    position:fixed;
    width:100%;
    top: 0;
    left: 0;
    z-index:10;
    background-color:#fff;
    border-bottom: 1rpx solid #e5e5e5;
    display: flex;
}

.e-head .w{
    flex: 1;
    font-size: 24rpx;
    text-align: center;
    height: 21px;
    line-height: 21px;
}

.e-head .s{
    color: #fe9808;
}

.e-month {
    background: #fff;
}

.e-month .b-header {
    text-align: center;
    font-size: 18px;
    height: 30px;
    line-height: 30px;
    border-top: 1px solid #dce1e6;
    padding-top: 8px;
}
.e-month .b-header:first-child {
    border-top: 0;
}
.e-month .b-row {
    margin: 0 2px;
    display: flex;
}

.e-month .b-row .item{
    flex: 1;
    width: 0;
    position: relative;
    margin-bottom: 5px;
    font-size: 18px;
    text-align: center;
    height: 60px;
    line-height: 60px;
    border-radius: 4px;
    z-index: 1;
    text-align: center;
}

.multi .e-month .b-row .item.select,
.multi .e-month .b-row .item-a:active {
    background-color: #f5f5f5;
    width: 90%;
}
.multi .e-month .b-row .item.select .day,
.multi .e-month .b-row .item.select .holiday,
.multi .e-month .b-row .item.select .ban,
.multi .e-month .b-row .item.select .xiu,
.multi .e-month .b-row .item.select .text,
.multi .e-month .b-row .item-a:active {
    color: #00bcd4;
}

.e-month .b-row .day{

}

.e-month .b-row .text,
.e-month .b-row .highlight{
    position: absolute;
    font-size: 11px;
    transform: scale(0.92);
    left: 0;
    text-align: center;
    bottom: 22px;
    height: 20px;
    color: #666;
    width: 100%;
    color: #888;
}

.e-month .b-row .text .rmb {
    color: #888;
}

.e-month .b-row .highlight,
.e-month .b-row .highlight .rmb{
    color: #fe9808;
}

.e-month .b-row .holiday,
.e-month .b-row .ban,
.e-month .b-row .xiu{
    position: absolute;
    top: 3px;
    left: 0;
    display: block;
    width: 100%;
    height: 20px;
    line-height: 20px;
    font-size: 11px;
    transform: scale(0.92);
    color: #fe9808;
}

.e-month .b-row .ban{
    color: #bbb;
}

.e-month .b-row .disabled,
.e-month .b-row .disabled .holiday,
.e-month .b-row .disabled .ban,
.e-month .b-row .disabled .xiu{
    color: #c7ced4;
}

.e-month .b-row .weekend{
    color: #fe9808;
}

.e-month .b-row .select,
.e-month .b-row .item-a:active{
    color: #fff;
    background: #11b4ca;
}
.e-month .b-row .select-second {
    color: #fff;
    background: #ccc;
}

.e-month .b-row .select .holiday,
.e-month .b-row .select .ban,
.e-month .b-row .select .xiu,
.e-month .b-row .select .text,
.e-month .b-row .select .text .rmb{
    color: #fff;
}
.multi .e-month .b-row .disabled:active,
.e-month .b-row .disabled:active{
    color: #c7ced4;
    background: #fff;
}

.e-btn {
    position: fixed;
    z-index: 9999;
    bottom: 0;
    width: 100%;
    height: 50px;
    line-height: 50px;
    text-align: center;
    font-size: 17px;
    background-color: #ff9705;
    color: #fff;
}
.e-btn:active {
    background-color: #cc7904;
}
.e-btn-padding {
    height: 50px;
}
```
